[plugin]
class = "io.gayal.restrictor.ImportRestrictionPlugin"

[[dependency]]
path = "/Users/gayaldassanayake/Documents/devrel/import_restriction/ImportRestrictor/build/libs/ImportRestrictor-1.0-SNAPSHOT.jar"
